server:
  port: 8080
spring:
  application:
    name: java-db-test
#   datasource:
#     url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#   h2:
#     console:
#       enabled: true
#       path: /h2-console
#   sql:
#     init:
#       mode: embedded
#       encoding: UTF-8
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
  sql:
    init:
      mode: always
      encoding: UTF-8
  data:
    redis:
      lettuce:
        pool:
          enabled: true
          max-active: 50       # max connections
          max-idle: 10         # max idle connections
          min-idle: 5          # min idle connections
          max-wait: 2000ms     # wait time before exception
